switch from nose to pytest
bbangert/routes pull request #107
Opened 2021-08-03 13:47 UTC by ktdreyer

Nose is deprecated. Use pytest for the test suite instead.

Fixes: #105

2022-05-22 08:38 UTC, mgorny requested changes
Thanks for doing this. Overall, great work. Just one minor nit: it causes `tests` to be installed into site-packages.

A simple way to avoid that would be not to add these `__init__.py` files — pytest doesn't need them anyway.

2022-05-22 08:39 UTC, mgorny commented
@kloczek, you seem to either be missing `repoze.lru` dependency or be hitting namespace problems.

2022-05-22 10:52 UTC, kloczek commented
> @kloczek, you seem to either be missing `repoze.lru` dependency or be hitting namespace problems.

`<censored>` .. yeah. One sec will repeat that wit h added `repoze-lru` to package BuildRequires.
Sorry my fault 😞

2022-05-22 10:55 UTC, kloczek commented
OK I found that already fixed that in my spec file 😋 
Updated pytest output
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-routes-2.5.1-3.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-routes-2.5.1-3.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/routes-2.5.1
collected 211 items

tests/test_functional/test_explicit_use.py .............                                                                                                             [  6%]
tests/test_functional/test_generation.py .................................................                                                                           [ 29%]
tests/test_functional/test_middleware.py .......                                                                                                                     [ 32%]
tests/test_functional/test_nonminimization.py .........                                                                                                              [ 36%]
tests/test_functional/test_recognition.py ..........................................................                                                                 [ 64%]
tests/test_functional/test_resources.py ...........                                                                                                                  [ 69%]
tests/test_functional/test_submapper.py ............                                                                                                                 [ 75%]
tests/test_functional/test_utils.py .........................................                                                                                        [ 94%]
tests/test_units/test_base.py ..                                                                                                                                     [ 95%]
tests/test_units/test_environment.py .                                                                                                                               [ 96%]
tests/test_units/test_mapper_str.py .                                                                                                                                [ 96%]
tests/test_units/test_route_escapes.py .......                                                                                                                       [100%]

============================================================================= warnings summary =============================================================================
tests/test_functional/test_generation.py:204
tests/test_functional/test_generation.py:204
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_generation.py:204: DeprecationWarning: invalid escape sequence \d
    requirements={'month':'\d{1,2}','day':'\d{1,2}'})

tests/test_functional/test_generation.py:219
tests/test_functional/test_generation.py:219
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_generation.py:219: DeprecationWarning: invalid escape sequence \d
    requirements={'month':'\d{1,2}','day':'\d{1,2}'})

tests/test_functional/test_generation.py:245
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_generation.py:245: DeprecationWarning: invalid escape sequence \d
    m.connect('articles/page/:page', controller='articles', action='index', requirements = {'page':'\d+'})

tests/test_functional/test_generation.py:248
tests/test_functional/test_generation.py:248
tests/test_functional/test_generation.py:248
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_generation.py:248: DeprecationWarning: invalid escape sequence \d
    requirements = {'year':'\d{4}', 'month':'\d{1,2}','day':'\d{1,2}'})

tests/test_functional/test_generation.py:284
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_generation.py:284: DeprecationWarning: invalid escape sequence \d
    m.connect('articles/page/:(page).myt', controller='articles', action='index', requirements = {'page':'\d+'})

tests/test_functional/test_generation.py:287
tests/test_functional/test_generation.py:287
tests/test_functional/test_generation.py:287
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_generation.py:287: DeprecationWarning: invalid escape sequence \d
    requirements = {'year':'\d{4}', 'month':'\d{1,2}','day':'\d{1,2}'})

tests/test_functional/test_generation.py:323
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_generation.py:323: DeprecationWarning: invalid escape sequence \d
    m.connect('articles/page/:page', controller='articles', action='index', requirements = {'page':'\d+'})

tests/test_functional/test_generation.py:326
tests/test_functional/test_generation.py:326
tests/test_functional/test_generation.py:326
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_generation.py:326: DeprecationWarning: invalid escape sequence \d
    requirements = {'year':'\d{4}', 'month':'\d{1,2}','day':'\d{1,2}'})

tests/test_functional/test_generation.py:497
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_generation.py:497: DeprecationWarning: invalid escape sequence \d
    m.connect('test/:year', controller='post', action='show', year=None, requirements = {'year':'\d{4}'})

tests/test_functional/test_generation.py:673
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_generation.py:673: DeprecationWarning: invalid escape sequence \d
    m.connect('articles/page/:page', controller='articles', action='index', requirements = {'page':'\d+'})

tests/test_functional/test_generation.py:676
tests/test_functional/test_generation.py:676
tests/test_functional/test_generation.py:676
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_generation.py:676: DeprecationWarning: invalid escape sequence \d
    requirements = {'year':'\d{4}', 'month':'\d{1,2}','day':'\d{1,2}'})

tests/test_functional/test_nonminimization.py:91
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_nonminimization.py:91: DeprecationWarning: invalid escape sequence \d
    m.connect('/{controller}/{action}/{id:\d\d}')

tests/test_functional/test_recognition.py:212
tests/test_functional/test_recognition.py:212
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_recognition.py:212: DeprecationWarning: invalid escape sequence \d
    requirements={'month':'\d{1,2}','day':'\d{1,2}'})

tests/test_functional/test_recognition.py:228
tests/test_functional/test_recognition.py:228
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_recognition.py:228: DeprecationWarning: invalid escape sequence \d
    requirements={'month':'\d{1,2}','day':'\d{1,2}'})

tests/test_functional/test_recognition.py:245
tests/test_functional/test_recognition.py:245
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_recognition.py:245: DeprecationWarning: invalid escape sequence \d
    requirements={'month':'\d{1,2}','day':'\d{1,2}'})

tests/test_functional/test_recognition.py:261
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_recognition.py:261: DeprecationWarning: invalid escape sequence \d
    requirements={'month':'\d{1,2}'})

tests/test_functional/test_recognition.py:262
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/tests/test_functional/test_recognition.py:262: DeprecationWarning: invalid escape sequence \d
    m.connect('view/:id/:controller', controller='blog', id=2, action='view', requirements={'id':'\d{1,2}'})

tests/test_functional/test_recognition.py:276
  /home/tkloczko/rpmbuild/BUILD/routes-2.5.1/t [...]

2023-05-17 15:51 UTC, ktdreyer commented
@mgorny thanks for the suggestion. I've removed the empty `__init__.py` files and re-pushed this.

2023-05-23 13:02 UTC, jcapiitao commented
Thanks @ktdreyer , could we have this merged and included in new release please ?

2025-05-19 05:27 UTC, bbangert approved these changes

2025-05-19 05:29 UTC, merged